export const LOAD_PODCAST_EPISODE = 'LOAD_PODCAST_EPISODE';
export const ADD_PODCASTS = 'ADD_PODCASTS';
export const ADD_PODCAST_EPISODE = 'ADD_PODCAST_EPISODE';
export const CHANGE_PLAYLIST_INDEX = 'CHANGE_PLAYLIST_INDEX';
export const MUTATE_PLAYLIST = 'MUTATE_PLAYLIST';
